apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-reelatable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flutter-reelatable
  template:
    metadata:
      labels:
        app: flutter-reelatable
    spec:
      # imagePullSecrets:
      # - name: gcr-json-key
      containers:
      - name: flutter-reelatable
        image: gcr.io/reelatable/docker-flutter-reelatable:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - containerPort: 80

