name: Deploy to GKE on PR

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.4.0
      with:
        service_account_key: ${{ secrets.GKE_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker --quiet

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GKE_PROJECT }}/flutter-reelatable:latest .
        docker push gcr.io/${{ secrets.GKE_PROJECT }}/flutter-reelatable:latest

    - name: Set up kubectl
      run: |
        gcloud components update kubectl
        gcloud container clusters get-credentials reelatable-cluster --zone us-west1 --project ${{ secrets.GKE_PROJECT }}

    - name: Deploy to Kubernetes
      run: |
        kubectl rollout restart deployment/flutter-reelatable