name: Deploy to GKE on PR

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.4.0
      with:
        service_account_key: ${{ secrets.GKE_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GKE_PROJECT }}/flutter-reelatable:$GITHUB_SHA .

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker --quiet

    - name: List Docker Config
      run: cat ~/.docker/config.json

    - name: Auth Info
      run: gcloud auth list

    - name: Print Project Info
      run: gcloud config list project

    - name: Push Docker image to Google Container Registry
      run: |
        echo ${{ secrets.GKE_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/${{ secrets.GKE_PROJECT }}/flutter-reelatable:$GITHUB_SHA

    - name: Set up kubectl
      run: |
        gcloud components update kubectl
        gcloud container clusters get-credentials reelatable-cluster --zone us-west1 --project ${{ secrets.GKE_PROJECT }}

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/flutter-reelatable flutter-reelatable=gcr.io/${{ secrets.GKE_PROJECT }}/flutter-reelatable:$GITHUB_SHA